### ISSUE TITLE
 Fill in a field from page 2

### ISSUE THREAD

**Issue by rudddy** [Ghostfly/PDFFormsFiller#2]
There is a problem, even if the array of fields contains the page number, it fills up on page 1.
I corrected Converter.php as follows https://gist.github.com/rudddy/e17b20e5f72aefba437991cf97e6ef32

**Comment by uplg** [comment]
Please re-format the issue, closing this, PDFFormsFiller has been tested on 10+ pages forms, so you just mis-used something, your gist is not helping me at all
